### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 1003520                                             # 1280*28*28
video_max_pixels: 1003520
trust_remote_code: true
# infer_backend: vllm

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false

### dataset
dataset: text_en_cot,geollava_superrs
output_dir: ~/saves/Qwen2.5-VL-7B-Instruct/text_en_cot__geollava_superrs

# per_device_train_batch_size: 8
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
# gradient_accumulation_steps: 4
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]


template: qwen2_vl
cutoff_len: 32768
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 64
dataloader_num_workers: 4

### output

logging_steps: 10
save_steps: 10000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
learning_rate: 2.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
